_ru_en_mapping: dict[str, str] = {
    'А': 'A',
    'В': 'B',
    'С': 'C',
    # : 'D',
    'Е': 'E',
    # : 'F',
    # : 'G',
    'Н': 'H',
    # : 'I',
    # : 'J',
    'К': 'K',
    # : 'L',
    'М': 'M',
    # : 'N',
    'О': 'O',
    'Р': 'P',
    # : 'Q',
    # : 'R',
    # : 'S',
    'Т': 'T',
    # : 'U',
    # : 'V',
    # : 'W',
    'Х': 'X',
    'У': 'Y',
    # : 'Z',
    'а': 'a',
    # : 'b',
    'с': 'c',
    # : 'd',
    'е': 'e',
    # : 'f',
    # : 'g',
    # : 'h',
    # : 'i',
    # : 'j',
    'к': 'k',
    # : 'l',
    'м': 'm',
    'п': 'n',
    'о': 'o',
    'р': 'p',
    # : 'q',
    'г': 'r',
    # : 's',
    'т': 't',
    # : 'u',
    # : 'v',
    # : 'w',
    'х': 'x',
    'у': 'y',
    # : 'z'
}


def to_en_chars(string: str) -> str:
    intersection = set(string) & set(_ru_en_mapping.keys())
    for char in intersection:
        string = string.replace(char, _ru_en_mapping[char])
    return string
